name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - run: npm install --frozen-lockfile

      - name: Build
        run: npm run docs:build

      - name: Deploy
        uses: appleboy/scp-action@v0.0.1
        with:
          host: ${{ secrets.USER_HOST}}
          username: ${{ secrets.USER_NAME }}
          password: ${{ secrets.USER_PASS}}
          post: 22
          source: "docs/"
          target: ${{ secrets.USER_TARGET }}
          github_token: ${{ secrets.USER_TOKEN }}
          publish_dir: docs/.vitepress/dist
          # cname: blog.gogogo7.com # if wanna deploy to custom domain
